version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # port für AMQP ( für Spring Boot)
      - "15672:15672"   # port für Web UI (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: admin     # user
      RABBITMQ_DEFAULT_PASS: admin     # password
