
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP (Spring Boot)
      - "15672:15672"   # Web UI (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  postgresdb:
    image: postgres:15
    container_name: postgresdb
    ports:
      - "5432:5432"     # PostgreSQL
    environment:
      POSTGRES_USER: energy_user
      POSTGRES_PASSWORD: energy_pass
      POSTGRES_DB: energydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
